# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core_messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'core_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ore_messages.proto\x12\x07metrics\"\xa5\x01\n\tBatchData\x12\r\n\x05\x65poch\x18\x01 \x01(\r\x12\x11\n\tbatch_idx\x18\x02 \x01(\r\x12\"\n\x06images\x18\x03 \x03(\x0b\x32\x12.metrics.ImageData\x12(\n\x0bpredictions\x18\x04 \x03(\x0b\x32\x13.metrics.Prediction\x12\x14\n\x0cground_truth\x18\x05 \x03(\x05\x12\x12\n\nbatch_loss\x18\x06 \x01(\x02\" \n\tImageData\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\"9\n\nPrediction\x12\x17\n\x0fpredicted_class\x18\x01 \x01(\x05\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"J\n\tEpochData\x12\r\n\x05\x65poch\x18\x01 \x01(\r\x12\x14\n\x0c\x61verage_loss\x18\x02 \x01(\x02\x12\x18\n\x10\x61verage_accuracy\x18\x03 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATCHDATA']._serialized_start=33
  _globals['_BATCHDATA']._serialized_end=198
  _globals['_IMAGEDATA']._serialized_start=200
  _globals['_IMAGEDATA']._serialized_end=232
  _globals['_PREDICTION']._serialized_start=234
  _globals['_PREDICTION']._serialized_end=291
  _globals['_EPOCHDATA']._serialized_start=293
  _globals['_EPOCHDATA']._serialized_end=367
# @@protoc_insertion_point(module_scope)
